name: CD Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      # 🔹 ソースコード取得（必須）
      - name: Checkout
        uses: actions/checkout@v4

      # 🔹 タグ生成（v1, v2, v3...）
      - name: Set tag
        id: vars
        run: echo "TAG=v${{ github.run_number }}" >> $GITHUB_OUTPUT

      # 🔹 DockerHubログイン
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 🔹 Dockerイメージビルド
      - name: Build image
        run: |
          docker build -t shiitake831dev/api-study:${{ steps.vars.outputs.TAG }} .

      # 🔹 DockerHubへPush
      - name: Push image
        run: |
          docker push shiitake831dev/api-study:${{ steps.vars.outputs.TAG }}

      # 🔹 EC2へデプロイ（ここが本番）
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}      # EC2のIP
          username: ubuntu                  # 通常はubuntu
          key: ${{ secrets.EC2_SSH_KEY }}   # 秘密鍵
          script: |
            cd /home/ubuntu/deploy

            # 最新タグへ更新
            sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=${{ steps.vars.outputs.TAG }}/" .env

            # 最新イメージ取得＆再起動
            docker compose pull
            docker compose up -d